### ISSUE TITLE
Fixtures not (re)loaded and transaction not reverting changes

### ISSUE THREAD

**Issue by CamJN** [blowmage/minitest-rails#184]
I have a test suite that is driving me crazy. I delete some fixture-created dependent objects in one test, and they are not restored for the other tests. "can access link for #{a} from article" fails whenever it's run after "destroying #{a} destroys links it owns" for the same article (which happens bc test order is randomized; which is a good thing in theory). Example is minimal reproducible example.

tests:
```
require 'test_helper'

class ArticleTest < ActiveSupport::TestCase
  test "ensure fixtures loaded" do
    assert_not_empty Article.all
  end
  Article.all.each do |a|
    test "can access link for #{a} from article" do
      assert_not_empty a.links
    end
    test "destroying #{a} destroys links it owns" do
      assert_difference('Link.all.length',-1) do
        a.destroy
      end
    end
  end
end
```

articles fixtures:
```
a_one:
  body: MyText
  title: MyString

a_two:
  body: MyText2
  title: MyString2
```

links fixtures:
```
l_one:
  url: 'http://mystring.com'
  text: MyString
  article: a_one

l_two:
  url: 'http://mystring.com/2'
  text: MyString2
  article: a_two
```

article model:
```
class Article < ActiveRecord::Base
  has_many :links, dependent: :delete_all
end
```
link model:
```
class Link < ActiveRecord::Base
  belongs_to :article
end
```
